import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fs-IR" dir="rtl">
      <body className="text-zinc-500">
        {children}
      </body>
    </html>
  );
}
